### ISSUE TITLE
AI Game Jam Submission

### ISSUE THREAD

**Issue by avivajpeyi** [avivajpeyi/LudumDare48#12]
# Notes
The theme of the GameJam is "Break the rules". In my game, the player breaks the rules of robotics and rolls over enemies.

# Tasks
## 1. Roll Character
- [X] Import Roll-Charcter code 
- [x] Adjust gameplay to use Roll-Character code
## 2. Asimov's Three Laws
- [x] Intro scene with the [3 laws](https://en.wikipedia.org/wiki/Three_Laws_of_Robotics)
- [x] Animation of "A robot may injure a human being" text remaining
## 3. Aesthetics
- [x] Change ball to [robo-sphere](https://assetstore.unity.com/packages/3d/characters/robots/robot-sphere-136226)
- [x] Change cubes to low-poly humanoid (glass runner is fine)
- [x] Better Start scene

**Comment by avivajpeyi** [comment]
#13 adds in the ability to use the click controller in the game
